apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-ace-cluster-1
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ace-web
  template:
    metadata:
      labels:
        app: ace-web
    spec:
      containers:
        - name: back-end
          image: 498939148594.dkr.ecr.us-west-2.amazonaws.com/xpod-ace-rcp:v2
          ports:
            - containerPort: 12345
